[package]
name = "backend-ai-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8.3"
alloy = { version = "0.13.0", features = ["full"] }
eyre = "0.6.12"
